# Generated by Django 2.2.1 on 2019-06-06 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_comentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comentario_Blog',
        ),
        migrations.RenameField(
            model_name='comentario_blog',
            old_name='post',
            new_name='postId',
        ),
    ]
