# Generated by Django 2.2.1 on 2019-06-07 00:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_dislikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario_Blog',
            new_name='ComentarioBlog',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='num_dislikes',
            new_name='numDislikes',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='num_likes',
            new_name='numLikes',
        ),
        migrations.RenameField(
            model_name='comentarioblog',
            old_name='postId',
            new_name='post',
        ),
        migrations.DeleteModel(
            name='Dislikes',
        ),
    ]
