# Generated by Django 2.2.1 on 2019-06-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_estadisticas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='num_comentarios',
            new_name='numComentarios',
        ),
        migrations.RenameField(
            model_name='estadisticas',
            old_name='num_visitas',
            new_name='numVisitas',
        ),
    ]
